eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/
server:
  port: 9100
spring:
  application:
    name: server-baiqiqi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.112.227:3306/practice
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: 47.96.112.227
    port: 6379
    database: 1