eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/
server:
  port: 9102
spring:
  application:
    name: zuul-baiqiqi
zuul:
  routes:
    client:
      path: /client/**
      serviceId: client-baiqiqi
    service:
      path: /server/**
      serviceId: server-baiqiqi